import { useState } from "react";
import { BookOpen, Calculator, FlaskConical, Globe2, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { academy, courseTabs, pillars, whatsappUrl } from "@/data/content";
import { SectionHeading, iconFor } from "./shared";

const classroomImage = "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1100&q=80";
const studentImage = "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80";

export function AboutCourses() {
  const [active, setActive] = useState(0);
  return <>
    <section id="about" className="scroll-mt-24 px-6 py-20 sm:py-28"><div className="mx-auto grid max-w-[1200px] items-center gap-14 lg:grid-cols-2 lg:gap-20"><div className="relative mx-auto w-full max-w-[520px]"><div className="aspect-[4/3] overflow-hidden rounded-2xl border border-gold/20"><img src={classroomImage} alt="Students learning in a bright coaching classroom" loading="lazy" className="h-full w-full object-cover" /></div><div className="absolute -bottom-10 -right-4 w-1/2 min-w-[160px] overflow-hidden rounded-2xl border-4 border-ink shadow-2xl sm:-right-8"><img src={studentImage} alt="Student writing notes during a lesson" loading="lazy" className="aspect-square h-full w-full object-cover" /></div></div><div><SectionHeading eyebrow="About Us" title="A Classroom Where" highlight="Doubts Are Welcome" /><div className="mt-7 space-y-5 text-sm leading-7 text-muted-copy"><p>Harshika Academy was started by Mohit Sarathe with a simple belief: a strong foundation matters more than memorised marks.</p><p>We keep batches small, explain the basics properly and stay in touch with parents. Students should leave class knowing what they learned and what to practise next.</p></div><div className="mt-9 grid gap-3">{pillars.map((pillar) => <div key={pillar.title} className="gold-border-glow rounded-2xl border border-gold/15 bg-ink-soft p-4"><div className="flex items-start gap-4"><div className="mt-1 grid size-9 shrink-0 place-items-center rounded-lg bg-gold/10 text-gold">{pillar.title === "Expert Guidance" ? <GraduationMark /> : pillar.title === "Concept Clarity" ? <Sparkles className="size-4" /> : <CheckMark />}</div><div><h3 className="font-utility text-sm font-semibold text-paper">{pillar.title}</h3><p className="mt-1 text-xs leading-6 text-muted-copy">{pillar.text}</p></div></div></div>)}</div></div></div></section>
    <section id="courses" className="scroll-mt-24 border-y border-gold/10 bg-ink-soft/60 px-6 py-20 sm:py-28"><div className="mx-auto max-w-[1200px]"><SectionHeading eyebrow="What We Teach" title="Courses &" highlight="Batches" intro="Clear teaching, regular practice and guidance suited to where your child is today." /><div className="mt-10 flex gap-1 overflow-x-auto border-b border-gold/15 pb-px">{courseTabs.map((tab, index) => <button key={tab.label} onClick={() => setActive(index)} className={`shrink-0 border-b-2 px-4 py-3 font-utility text-xs font-semibold uppercase tracking-wider transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold ${active === index ? "border-gold text-gold" : "border-transparent text-muted-copy hover:text-paper"}`}>{tab.label}</button>)}</div><div className="mt-8 grid gap-4 md:grid-cols-3">{courseTabs[active].subjects.map((subject) => <div key={subject.name} className="gold-border-glow rounded-2xl border border-gold/15 bg-ink p-6"><div className="mb-7 grid size-11 place-items-center rounded-xl bg-gold/10 text-gold">{iconFor(subject.icon)}</div><h3 className="font-utility text-lg font-semibold text-paper">{subject.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-muted-copy">{subject.description}</p><span className="mt-6 inline-flex rounded bg-gold/10 px-3 py-1 font-utility text-[10px] font-semibold uppercase tracking-wider text-gold">{subject.timing} Batch</span></div>)}</div><p className="mt-8 text-sm text-muted-copy">For batch timings and admission details, <a className="font-semibold text-gold underline underline-offset-4 hover:text-gold-bright" href={whatsappUrl} target="_blank" rel="noreferrer">message us on WhatsApp.</a></p></div></section>
  </>;
}
function GraduationMark() { return <span className="font-display text-sm">G</span>; }
function CheckMark() { return <span className="font-display text-sm">✓</span>; }
