import teacherImage from "@/assets/mohit-sarathe.jpg";
import { Check, GraduationCap } from "lucide-react";
import { academy, whatsappUrl } from "@/data/content";
import { SectionHeading } from "./shared";

export function FacultyAdmission() {
  return <>
    <section id="faculty" className="scroll-mt-24 overflow-hidden px-6 py-20 sm:py-28"><div className="mx-auto grid max-w-[1200px] items-center gap-14 lg:grid-cols-[0.85fr_1.15fr] lg:gap-20"><div className="relative mx-auto w-full max-w-[430px]"><div className="absolute -inset-7 rounded-[50%] border border-gold/20" /><div className="relative aspect-[3/4] overflow-hidden rounded-[2rem] border border-gold/20 bg-ink-soft"><img src={teacherImage} alt="Mohit Sarathe, CTET-qualified teacher at Harshika Academy" loading="lazy" width={1024} height={1280} className="h-full w-full object-cover" /></div><div className="absolute -bottom-8 -left-10 h-32 w-[135%] rounded-[50%] border-t border-gold/25" /></div><div><SectionHeading eyebrow="Meet Your Teacher" title="Mohit" highlight="Sarathe" /><div className="mt-6 flex flex-wrap gap-2">{["B.A.", "M.A.", "PGDCA", "D.El.Ed."].map((item) => <span key={item} className="rounded border border-gold/40 px-3 py-1.5 font-utility text-[10px] font-semibold uppercase tracking-wider text-paper">{item}</span>)}</div><div className="mt-5 inline-flex items-center gap-2 rounded bg-gold px-4 py-2 font-utility text-xs font-bold uppercase tracking-wider text-ink"><GraduationCap className="size-4" /> CTET Qualified</div><p className="mt-7 max-w-2xl text-base italic leading-8 text-muted-copy">“I want every student to feel safe asking a question. We take one concept at a time, use examples from daily life and move ahead only when the idea is clear.”</p><blockquote className="mt-8 border-l-2 border-gold pl-5 text-lg italic text-gold-bright">“A student who understands the 'why' never forgets the 'what'.”</blockquote></div></div></section>
    <section id="admission" className="border-y border-gold/10 bg-ink-soft/60 px-6 py-20 sm:py-24"><div className="mx-auto max-w-[1200px]"><SectionHeading eyebrow="Getting Started" title="Three Steps" highlight="to Join" align="center" /><div className="relative mt-12 grid gap-8 md:grid-cols-3 md:gap-10"><div className="absolute left-[16%] right-[16%] top-6 hidden h-px bg-gold/30 md:block" />{["Message or call us", "Attend a free demo class", "Confirm your seat"].map((step, index) => <div key={step} className="relative flex gap-4 md:block md:text-center"><div className="relative z-10 grid size-12 shrink-0 place-items-center rounded-full border border-gold bg-ink font-display text-xl text-gold">{index + 1}</div><div className="pt-1 md:pt-5"><h3 className="font-utility text-sm font-semibold text-paper">{step}</h3><p className="mt-2 max-w-xs text-sm leading-6 text-muted-copy md:mx-auto">{["Tell us your class and subjects.", "Sit in a real batch, no commitment.", "We share the timetable and you begin."][index]}</p></div></div>)}</div></div></section>
  </>;
}
