import { useEffect, useMemo, useState } from "react";
import { Expand, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { galleryItems, results } from "@/data/content";
import { ChevronLeft, ChevronRight, SectionHeading } from "./shared";

export function ResultsGallery() {
  const [resultIndex, setResultIndex] = useState(0);
  const [category, setCategory] = useState("All");
  const [lightbox, setLightbox] = useState<number | null>(null);
  const filtered = useMemo(() => category === "All" ? galleryItems : galleryItems.filter((item) => item.category === category), [category]);
  const nextImage = (step: number) => setLightbox((current) => current === null ? null : (current + step + filtered.length) % filtered.length);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (lightbox === null) return; if (event.key === "Escape") setLightbox(null); if (event.key === "ArrowRight") nextImage(1); if (event.key === "ArrowLeft") nextImage(-1); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [lightbox, filtered.length]);
  return <>
    <section id="results" className="scroll-mt-24 px-6 py-20 sm:py-28"><div className="mx-auto max-w-[1200px]"><div className="flex items-end justify-between gap-5"><SectionHeading eyebrow="Our Results" title="Students Who" highlight="Made It Count" /><div className="hidden gap-2 sm:flex"><Button variant="outline" size="icon" aria-label="Previous result" className="rounded-full border-gold/30 bg-transparent text-gold hover:bg-gold/10" onClick={() => setResultIndex((i) => Math.max(0, i - 1))}><ChevronLeft /></Button><Button variant="outline" size="icon" aria-label="Next result" className="rounded-full border-gold/30 bg-transparent text-gold hover:bg-gold/10" onClick={() => setResultIndex((i) => Math.min(results.length - 1, i + 1))}><ChevronRight /></Button></div></div><div className="mt-10 flex snap-x gap-4 overflow-x-auto pb-4" style={{ scrollBehavior: "smooth" }}>{results.map((item, index) => <article key={item.name} className={`min-w-[280px] snap-start overflow-hidden rounded-2xl border border-gold/15 bg-ink-soft sm:min-w-[330px] ${index === resultIndex ? "ring-1 ring-gold/40" : ""}`}><img src={item.image} alt={`${item.name}, ${item.className}`} loading="lazy" className="aspect-[4/3] w-full object-cover" /><div className="p-5"><p className="font-utility text-[10px] uppercase tracking-wider text-gold">{item.className}</p><h3 className="mt-2 font-utility font-semibold text-paper">{item.name}</h3><p className="mt-3 font-display text-2xl uppercase text-gold">{item.result}</p><p className="mt-2 text-xs text-muted-copy">{item.school}</p></div></article>)}</div></div></section>
    <section id="gallery" className="scroll-mt-24 border-y border-gold/10 bg-ink-soft/50 px-6 py-20 sm:py-28"><div className="mx-auto max-w-[1200px]"><SectionHeading eyebrow="Inside the Academy" title="Gallery" highlight="" intro="A glimpse of the calm, focused place where classes happen." /><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{["All", "Classroom", "Events", "Achievements", "Facilities"].map((item) => <button key={item} onClick={() => { setCategory(item); setLightbox(null); }} className={`shrink-0 rounded-full border px-4 py-2 font-utility text-[10px] font-semibold uppercase tracking-wider transition ${category === item ? "border-gold bg-gold text-ink" : "border-gold/25 text-gold hover:bg-gold/10"}`}>{item}</button>)}</div><div className="mt-8 columns-1 gap-4 sm:columns-2 lg:columns-3">{filtered.map((item, index) => <button key={item.src} onClick={() => setLightbox(index)} className="group relative mb-4 block w-full overflow-hidden rounded-xl border border-gold/15 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold"><img src={item.src} alt={item.caption} loading="lazy" className="block h-auto w-full transition duration-500 group-hover:scale-[1.03]" /><span className="absolute inset-0 flex items-end justify-between bg-gradient-to-t from-ink/90 via-transparent to-transparent p-4 opacity-0 transition-opacity group-hover:opacity-100"><span className="font-utility text-xs text-paper">{item.caption}</span><Expand className="size-4 shrink-0 text-gold" aria-hidden="true" /></span></button>)}</div></div></section>
    {lightbox !== null && filtered[lightbox] && <div role="dialog" aria-modal="true" aria-label="Gallery image" className="fixed inset-0 z-[100] flex items-center justify-center bg-ink/95 p-5 backdrop-blur-md" onClick={() => setLightbox(null)}><div className="relative flex max-h-full w-full max-w-5xl items-center justify-center" onClick={(event) => event.stopPropagation()}><img src={filtered[lightbox].src} alt={filtered[lightbox].caption} className="max-h-[78vh] max-w-full rounded-xl object-contain" /><Button variant="ghost" size="icon" aria-label="Close gallery" onClick={() => setLightbox(null)} className="absolute right-0 top-0 text-paper hover:bg-accent hover:text-gold"><X /></Button><Button variant="ghost" size="icon" aria-label="Previous image" onClick={() => nextImage(-1)} className="absolute left-0 top-1/2 -translate-y-1/2 rounded-full bg-ink/60 text-paper hover:bg-gold hover:text-ink"><ChevronLeft /></Button><Button variant="ghost" size="icon" aria-label="Next image" onClick={() => nextImage(1)} className="absolute right-0 top-1/2 -translate-y-1/2 rounded-full bg-ink/60 text-paper hover:bg-gold hover:text-ink"><ChevronRight /></Button><div className="absolute bottom-0 left-1/2 -translate-x-1/2 bg-ink/80 px-4 py-3 text-center"><p className="font-utility text-sm text-paper">{filtered[lightbox].caption}</p><p className="mt-1 font-utility text-[10px] uppercase tracking-widest text-gold">{lightbox + 1} / {filtered.length}</p></div></div></div>}
  </>;
}
