import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { faqs, testimonials } from "@/data/content";
import { ChevronDown, ChevronLeft, ChevronRight, SectionHeading } from "./shared";

export function TestimonialsFaq() {
  const [testimonial, setTestimonial] = useState(0);
  const [faq, setFaq] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setTestimonial((value) => (value + 1) % testimonials.length), 6000); return () => window.clearInterval(timer); }, []);
  return <>
    <section id="testimonials" className="px-6 py-20 sm:py-28"><div className="mx-auto max-w-[900px] text-center"><SectionHeading eyebrow="Testimonials" title="Words From Parents" highlight="& Students" align="center" /><div className="relative mt-10 rounded-2xl border border-gold/15 bg-ink-soft px-6 py-10 sm:px-16"><p className="font-display text-2xl uppercase leading-tight text-paper sm:text-3xl">“{testimonials[testimonial].quote}”</p><div className="mt-8 flex items-center justify-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-gold/15 font-utility text-xs font-bold text-gold">{testimonials[testimonial].initials}</div><div className="text-left"><p className="font-utility text-sm font-semibold text-paper">{testimonials[testimonial].name}</p><p className="text-xs text-muted-copy">{testimonials[testimonial].relation}</p></div></div><div className="mt-8 flex items-center justify-center gap-2">{testimonials.map((item, index) => <button key={item.name} aria-label={`Show testimonial ${index + 1}`} onClick={() => setTestimonial(index)} className={`size-2 rounded-full transition ${index === testimonial ? "bg-gold" : "bg-gold/25"}`} />)}</div><Button variant="ghost" size="icon" aria-label="Previous testimonial" onClick={() => setTestimonial((testimonial - 1 + testimonials.length) % testimonials.length)} className="absolute left-2 top-1/2 -translate-y-1/2 text-gold hover:bg-gold/10"><ChevronLeft /></Button><Button variant="ghost" size="icon" aria-label="Next testimonial" onClick={() => setTestimonial((testimonial + 1) % testimonials.length)} className="absolute right-2 top-1/2 -translate-y-1/2 text-gold hover:bg-gold/10"><ChevronRight /></Button></div></div></section>
    <section id="faq" className="border-y border-gold/10 bg-ink-soft/50 px-6 py-20 sm:py-28"><div className="mx-auto grid max-w-[1000px] gap-12 lg:grid-cols-[0.75fr_1.25fr] lg:gap-20"><SectionHeading eyebrow="Questions" title="Before You" highlight="Join" intro="A few things parents usually ask before the first class." /> <div className="divide-y divide-gold/15 border-y border-gold/15">{faqs.map((item, index) => <div key={item.question}><button aria-expanded={faq === index} onClick={() => setFaq(faq === index ? -1 : index)} className="flex w-full items-center justify-between gap-5 py-5 text-left font-utility text-sm font-semibold text-paper focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold"><span>{item.question}</span><ChevronDown className={`size-5 shrink-0 text-gold transition-transform ${faq === index ? "rotate-180" : ""}`} /></button><div className={`grid transition-[grid-template-rows] duration-300 ${faq === index ? "grid-rows-[1fr]" : "grid-rows-[0fr]"}`}><p className="overflow-hidden text-sm leading-7 text-muted-copy">{item.answer}</p></div></div>)}</div></div></section>
  </>;
}
